import { Subject, Announcement, CalendarEvent } from '@/src/types';

export const IE_SUBJECTS: Subject[] = [
  // FIRST YEAR - 1st Semester
  {
    id: 'emath-111',
    code: 'EMATH 111',
    name: 'Calculus 1',
    description: 'Differential calculus, limits, continuity, and derivatives.',
    units: 5,
    yearLevel: '1st',
    semester: '1st',
    prerequisiteIds: [],
    department: 'Mathematics',
    rating: 4.8,
    reviewCount: 124,
    slotsAvailable: 15,
    totalSlots: 45,
    isFavorite: true,
    syllabusUrl: 'https://example.com/syllabus/emath-111.pdf',
    icon: 'Calculator'
  },
  {
    id: 'echem',
    code: 'ECHEM',
    name: 'Chemistry for Engineering (Lec)',
    description: 'Fundamental principles of chemistry for engineering students.',
    units: 3,
    yearLevel: '1st',
    semester: '1st',
    prerequisiteIds: [],
    department: 'Chemistry',
    rating: 4.2,
    reviewCount: 89,
    slotsAvailable: 5,
    totalSlots: 40,
    syllabusUrl: 'https://example.com/syllabus/echem.pdf',
    icon: 'FlaskConical'
  },
  {
    id: 'echeml',
    code: 'ECHEML',
    name: 'Chemistry for Engineering (Lab)',
    description: 'Laboratory experiments in chemistry.',
    units: 1,
    yearLevel: '1st',
    semester: '1st',
    prerequisiteIds: [],
    department: 'Chemistry',
    rating: 4.5,
    reviewCount: 67,
    slotsAvailable: 2,
    totalSlots: 20,
    syllabusUrl: 'https://example.com/syllabus/echeml.pdf',
    icon: 'FlaskConical'
  },
  {
    id: 'bes-cfp',
    code: 'BES-CFP',
    name: 'Computer Fundamentals and Programming',
    description: 'Introduction to computer systems and basic programming concepts.',
    units: 2,
    yearLevel: '1st',
    semester: '1st',
    prerequisiteIds: [],
    department: 'Computer Science',
    rating: 4.9,
    reviewCount: 210,
    slotsAvailable: 0,
    totalSlots: 40,
    isFavorite: true,
    syllabusUrl: 'https://example.com/syllabus/bes-cfp.pdf',
    icon: 'Monitor'
  },
  {
    id: 'ie-ipc-111',
    code: 'IE-IPC 111',
    name: 'Introduction to Engineering',
    description: 'Overview of the engineering profession and IE field.',
    units: 2,
    yearLevel: '1st',
    semester: '1st',
    prerequisiteIds: [],
    rating: 4.5,
    reviewCount: 112,
    averageRating: 4.5,
    ratingCount: 112,
    syllabusUrl: 'https://example.com/syllabus/ie-ipc-111.pdf',
    isAvailable: true,
    topics: ['Engineering Profession', 'IE Basics', 'History of IE'],
    icon: 'Building2'
  },
  {
    id: 'ie-ac-111',
    code: 'IE-AC 111',
    name: 'Principles of Economics',
    description: 'Basic economic theories and their applications.',
    units: 3,
    yearLevel: '1st',
    semester: '1st',
    prerequisiteIds: [],
    rating: 4.3,
    reviewCount: 88,
    syllabusUrl: 'https://example.com/syllabus/ie-ac-111.pdf',
    icon: 'Coins'
  },
  {
    id: 'ie-tech-111',
    code: 'IE-TECH 111',
    name: 'Pneumatics and Programmable Logic Controller',
    description: 'Control systems using pneumatics and PLCs.',
    units: 3,
    yearLevel: '1st',
    semester: '1st',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/ie-tech-111.pdf',
    icon: 'Cpu'
  },
  {
    id: 'pe-1',
    code: 'PE 1',
    name: 'Physical Education 1',
    description: 'Physical fitness and self-testing activities.',
    units: 2,
    yearLevel: '1st',
    semester: '1st',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/pe-1.pdf',
    icon: 'Dumbbell'
  },
  {
    id: 'nstp-1',
    code: 'NSTP 1',
    name: 'National Service Training Program',
    description: 'Civic consciousness and defense preparedness.',
    units: 3,
    yearLevel: '1st',
    semester: '1st',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/nstp-1.pdf',
    icon: 'Shield'
  },

  // FIRST YEAR - 2nd Semester
  {
    id: 'emath-122',
    code: 'EMATH 122',
    name: 'Calculus 2',
    description: 'Integral calculus and its applications.',
    units: 5,
    yearLevel: '1st',
    semester: '2nd',
    prerequisiteIds: ['emath-111'],
    syllabusUrl: 'https://example.com/syllabus/emath-122.pdf',
    icon: 'Calculator'
  },
  {
    id: 'ephys',
    code: 'EPHYS',
    name: 'Physics for Engineers (Lec)',
    description: 'Mechanics, heat, and sound for engineers.',
    units: 3,
    yearLevel: '1st',
    semester: '2nd',
    prerequisiteIds: ['emath-111'],
    syllabusUrl: 'https://example.com/syllabus/ephys.pdf',
    icon: 'CloudLightning'
  },
  {
    id: 'ephysl',
    code: 'EPHYSL',
    name: 'Physics for Engineers (Lab)',
    description: 'Laboratory experiments in physics.',
    units: 1,
    yearLevel: '1st',
    semester: '2nd',
    prerequisiteIds: ['emath-111'],
    syllabusUrl: 'https://example.com/syllabus/ephysl.pdf',
    icon: 'CloudLightning'
  },
  {
    id: 'bes-cad',
    code: 'BES-CAD',
    name: 'Computer-Aided Drafting',
    description: 'Technical drawing using CAD software.',
    units: 1,
    yearLevel: '1st',
    semester: '2nd',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/bes-cad.pdf',
    icon: 'PenTool'
  },
  {
    id: 'ie-pc-121',
    code: 'IE - PC 121',
    name: 'Statistical Analysis for Industrial Engineering 1',
    description: 'Probability and descriptive statistics.',
    units: 3,
    yearLevel: '1st',
    semester: '2nd',
    prerequisiteIds: [],
    rating: 4.1,
    reviewCount: 92,
    syllabusUrl: 'https://example.com/syllabus/ie-pc-121.pdf',
    icon: 'BarChart'
  },
  {
    id: 'ie-iac-121',
    code: 'IE - IAC 121',
    name: 'Basic Accounting',
    description: 'Introduction to accounting principles.',
    units: 3,
    yearLevel: '1st',
    semester: '2nd',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/ie-iac-121.pdf',
    icon: 'BookOpen'
  },
  {
    id: 'gec-pc',
    code: 'GEC - PC',
    name: 'Purposive Communication',
    description: 'Effective communication in various contexts.',
    units: 3,
    yearLevel: '1st',
    semester: '2nd',
    prerequisiteIds: [],
    rating: 4.4,
    reviewCount: 156,
    syllabusUrl: 'https://example.com/syllabus/gec-pc.pdf',
    icon: 'MessageSquare'
  },
  {
    id: 'gec-us',
    code: 'GEC - US',
    name: 'Understanding the Self',
    description: 'Psychological and philosophical perspectives of the self.',
    units: 3,
    yearLevel: '1st',
    semester: '2nd',
    prerequisiteIds: [],
    rating: 4.6,
    reviewCount: 178,
    syllabusUrl: 'https://example.com/syllabus/gec-us.pdf',
    icon: 'User'
  },
  {
    id: 'pe-2',
    code: 'PE 2',
    name: 'Physical Education 2',
    description: 'Rhythmic activities and dance.',
    units: 2,
    yearLevel: '1st',
    semester: '2nd',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/pe-2.pdf',
    icon: 'Music'
  },
  {
    id: 'nstp-2',
    code: 'NSTP 2',
    name: 'National Service Training Program 2',
    description: 'Community immersion and service.',
    units: 3,
    yearLevel: '1st',
    semester: '2nd',
    prerequisiteIds: ['nstp-1'],
    syllabusUrl: 'https://example.com/syllabus/nstp-2.pdf',
    icon: 'ShieldCheck'
  },

  // SECOND YEAR - 1st Semester
  {
    id: 'emath-213',
    code: 'EMATH 213',
    name: 'Differential Equations',
    description: 'Solving first-order and higher-order differential equations.',
    units: 3,
    yearLevel: '2nd',
    semester: '1st',
    prerequisiteIds: ['emath-122'],
    syllabusUrl: 'https://example.com/syllabus/emath-213.pdf',
    icon: 'Variable'
  },
  {
    id: 'bes-emech',
    code: 'BES-EMECH',
    name: 'Engineering Mechanics',
    description: 'Statics and dynamics of rigid bodies.',
    units: 3,
    yearLevel: '2nd',
    semester: '1st',
    prerequisiteIds: ['ephys'],
    syllabusUrl: 'https://example.com/syllabus/bes-emech.pdf',
    icon: 'Settings'
  },
  {
    id: 'ie-pc-212',
    code: 'IE - PC 212',
    name: 'Industrial Materials and Processes',
    description: 'Study of materials used in industry and manufacturing processes.',
    units: 3,
    yearLevel: '2nd',
    semester: '1st',
    prerequisiteIds: ['echem', 'ephys'],
    rating: 4.2,
    reviewCount: 76,
    syllabusUrl: 'https://example.com/syllabus/ie-pc-212.pdf',
    icon: 'Factory'
  },
  {
    id: 'ie-pc-212l',
    code: 'IE - PC 212L',
    name: 'Industrial Materials and Processes (Lab)',
    description: 'Hands-on experiments with industrial materials.',
    units: 2,
    yearLevel: '2nd',
    semester: '1st',
    prerequisiteIds: ['echeml', 'ephysl'],
    syllabusUrl: 'https://example.com/syllabus/ie-pc-212l.pdf',
    icon: 'Beaker'
  },
  {
    id: 'ie-pc-213',
    code: 'IE - PC 213',
    name: 'Statistical Analysis for Industrial Engineering 2',
    description: 'Inferential statistics and hypothesis testing.',
    units: 3,
    yearLevel: '2nd',
    semester: '1st',
    prerequisiteIds: ['ie-pc-121'],
    syllabusUrl: 'https://example.com/syllabus/ie-pc-213.pdf',
    icon: 'Table'
  },
  {
    id: 'ie-pc-214',
    code: 'IE - PC 214',
    name: 'Industrial Organization and Management',
    description: 'Principles of management and organizational behavior.',
    units: 3,
    yearLevel: '2nd',
    semester: '1st',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/ie-pc-214.pdf',
    icon: 'Users'
  },
  {
    id: 'ie-ac-212',
    code: 'IE - AC 212',
    name: 'Financial Accounting',
    description: 'Preparation and analysis of financial statements.',
    units: 3,
    yearLevel: '2nd',
    semester: '1st',
    prerequisiteIds: ['ie-iac-121'],
    syllabusUrl: 'https://example.com/syllabus/ie-ac-212.pdf',
    icon: 'FileText'
  },
  {
    id: 'gec-mmw',
    code: 'GEC-MMW',
    name: 'Mathematics in the Modern World',
    description: 'Applications of mathematics in contemporary life.',
    units: 3,
    yearLevel: '2nd',
    semester: '1st',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/gec-mmw.pdf',
    icon: 'Globe'
  },
  {
    id: 'gee-tem',
    code: 'GEE - TEM',
    name: 'The Entrepreneurial Mind',
    description: 'Developing an entrepreneurial mindset and business basics.',
    units: 3,
    yearLevel: '2nd',
    semester: '1st',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/gee-tem.pdf',
    icon: 'Lightbulb'
  },
  {
    id: 'pe-3',
    code: 'PE 3',
    name: 'Physical Education 3',
    description: 'Individual and dual sports.',
    units: 2,
    yearLevel: '2nd',
    semester: '1st',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/pe-3.pdf',
    icon: 'Trophy'
  },

  // SECOND YEAR - 2nd Semester
  {
    id: 'ie-pc-225',
    code: 'IE - PC 225',
    name: 'Advanced Mathematics for Industrial Engineering',
    description: 'Complex variables, Laplace transforms, and Fourier series.',
    units: 3,
    yearLevel: '2nd',
    semester: '2nd',
    prerequisiteIds: ['emath-213'],
    syllabusUrl: 'https://example.com/syllabus/ie-pc-225.pdf',
    icon: 'FunctionSquare'
  },
  {
    id: 'ie-pc-226',
    code: 'IE - PC 226',
    name: 'Work Study and Measurement',
    description: 'Method study and work measurement techniques.',
    units: 4,
    yearLevel: '2nd',
    semester: '2nd',
    prerequisiteIds: ['ie-pc-212', 'ie-pc-213', 'ie-pc-214'],
    syllabusUrl: 'https://example.com/syllabus/ie-pc-226.pdf',
    icon: 'Timer'
  },
  {
    id: 'ie-pc-227',
    code: 'IE - PC 227',
    name: 'Information Systems',
    description: 'Design and management of industrial information systems.',
    units: 3,
    yearLevel: '2nd',
    semester: '2nd',
    prerequisiteIds: ['bes-cfp'],
    syllabusUrl: 'https://example.com/syllabus/ie-pc-227.pdf',
    icon: 'Database'
  },
  {
    id: 'ie-pc-228',
    code: 'IE - PC 228',
    name: 'System Dynamics',
    description: 'Modeling complex systems and feedback loops.',
    units: 3,
    yearLevel: '2nd',
    semester: '2nd',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/ie-pc-228.pdf',
    icon: 'Activity'
  },
  {
    id: 'ie-pe-221',
    code: 'IE - PE 221',
    name: 'Project Management',
    description: 'Planning, scheduling, and controlling projects.',
    units: 3,
    yearLevel: '2nd',
    semester: '2nd',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/ie-pe-221.pdf',
    icon: 'Calendar'
  },
  {
    id: 'bes-ee',
    code: 'BES-EE',
    name: 'Engineering Economics',
    description: 'Economic analysis of engineering projects.',
    units: 3,
    yearLevel: '2nd',
    semester: '2nd',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/bes-ee.pdf',
    icon: 'TrendingUp'
  },
  {
    id: 'gec-tcw',
    code: 'GEC - TCW',
    name: 'The Contemporary World',
    description: 'Globalization and its impact on the world.',
    units: 3,
    yearLevel: '2nd',
    semester: '2nd',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/gec-tcw.pdf',
    icon: 'Earth'
  },
  {
    id: 'gec-lwr',
    code: 'GEC - LWR',
    name: 'Life and Works of Rizal',
    description: 'Study of the life and writings of Jose Rizal.',
    units: 3,
    yearLevel: '2nd',
    semester: '2nd',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/gec-lwr.pdf',
    icon: 'History'
  },
  {
    id: 'gee-lie',
    code: 'GEE - LIE',
    name: 'Living in the IT Era',
    description: 'Impact of IT on society and daily life.',
    units: 3,
    yearLevel: '2nd',
    semester: '2nd',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/gee-lie.pdf',
    icon: 'Smartphone'
  },
  {
    id: 'pe-4',
    code: 'PE 4',
    name: 'Physical Education 4',
    description: 'Team sports.',
    units: 2,
    yearLevel: '2nd',
    semester: '2nd',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/pe-4.pdf',
    icon: 'Users2'
  },

  // THIRD YEAR - 1st Semester
  {
    id: 'ie-pc-319',
    code: 'IE - PC 319',
    name: 'Operations Research 1',
    description: 'Linear programming and optimization models.',
    units: 3,
    yearLevel: '3rd',
    semester: '1st',
    prerequisiteIds: ['ie-pc-225'],
    syllabusUrl: 'https://example.com/syllabus/ie-pc-319.pdf',
    icon: 'BarChart3'
  },
  {
    id: 'ie-pc-3110',
    code: 'IE - PC 3110',
    name: 'Quality Management Systems',
    description: 'Principles of TQM and quality control.',
    units: 3,
    yearLevel: '3rd',
    semester: '1st',
    prerequisiteIds: ['ie-pc-213', 'ie-pc-226'],
    syllabusUrl: 'https://example.com/syllabus/ie-pc-3110.pdf',
    icon: 'CheckCircle'
  },
  {
    id: 'ie-pc-3111',
    code: 'IE - PC 3111',
    name: 'Ergonomics 1',
    description: 'Human factors in engineering design.',
    units: 3,
    yearLevel: '3rd',
    semester: '1st',
    prerequisiteIds: ['ie-pc-226'],
    syllabusUrl: 'https://example.com/syllabus/ie-pc-3111.pdf',
    icon: 'Armchair'
  },
  {
    id: 'ie-pc-3112',
    code: 'IE - PC 3112',
    name: 'Operations Management 1',
    description: 'Production planning and inventory control.',
    units: 3,
    yearLevel: '3rd',
    semester: '1st',
    prerequisiteIds: ['ie-pc-319', 'ie-pc-3110'],
    syllabusUrl: 'https://example.com/syllabus/ie-pc-3112.pdf',
    icon: 'GanttChart'
  },
  {
    id: 'ie-ac-313',
    code: 'IE - AC 313',
    name: 'Managerial Accounting',
    description: 'Accounting for decision making and control.',
    units: 3,
    yearLevel: '3rd',
    semester: '1st',
    prerequisiteIds: ['ie-ac-212'],
    syllabusUrl: 'https://example.com/syllabus/ie-ac-313.pdf',
    icon: 'Briefcase'
  },
  {
    id: 'ie-ac-314',
    code: 'IE - AC 314',
    name: 'Thermodynamics',
    description: 'Laws of thermodynamics and energy conversion.',
    units: 3,
    yearLevel: '3rd',
    semester: '1st',
    prerequisiteIds: ['emath-122'],
    syllabusUrl: 'https://example.com/syllabus/ie-ac-314.pdf',
    icon: 'Thermometer'
  },
  {
    id: 'bes-t',
    code: 'BES - T',
    name: 'Technopreneurship 101',
    description: 'Entrepreneurship in the technology sector.',
    units: 3,
    yearLevel: '3rd',
    semester: '1st',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/bes-t.pdf',
    icon: 'Rocket'
  },
  {
    id: 'bes-osh',
    code: 'BES - OSH',
    name: 'Basic Occupational Safety and Health',
    description: 'Safety standards and health in the workplace.',
    units: 3,
    yearLevel: '3rd',
    semester: '1st',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/bes-osh.pdf',
    icon: 'HardHat'
  },
  {
    id: 'ie-ipc-312',
    code: 'IE - IPC 312',
    name: 'Methodology of Research',
    description: 'Research designs and data collection methods.',
    units: 3,
    yearLevel: '3rd',
    semester: '1st',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/ie-ipc-312.pdf',
    icon: 'Search'
  },

  // THIRD YEAR - 2nd Semester
  {
    id: 'ie-pc-3213',
    code: 'IE - PC 3213',
    name: 'Operations Research 2',
    description: 'Stochastic models and advanced optimization.',
    units: 3,
    yearLevel: '3rd',
    semester: '2nd',
    prerequisiteIds: ['ie-pc-319'],
    syllabusUrl: 'https://example.com/syllabus/ie-pc-3213.pdf',
    icon: 'BarChart3'
  },
  {
    id: 'ie-pc-3214',
    code: 'IE - PC 3214',
    name: 'Operations Management 2',
    description: 'Advanced production and service operations.',
    units: 4,
    yearLevel: '3rd',
    semester: '2nd',
    prerequisiteIds: ['ie-pc-3112'],
    syllabusUrl: 'https://example.com/syllabus/ie-pc-3214.pdf',
    icon: 'Layout'
  },
  {
    id: 'ie-pc-3215',
    code: 'IE - PC 3215',
    name: 'Ergonomics 2',
    description: 'Advanced topics in human-machine systems.',
    units: 3,
    yearLevel: '3rd',
    semester: '2nd',
    prerequisiteIds: ['ie-pc-3111'],
    syllabusUrl: 'https://example.com/syllabus/ie-pc-3215.pdf',
    icon: 'UserCircle'
  },
  {
    id: 'ie-ipc-323',
    code: 'IE - IPC 323',
    name: 'Research Writing',
    description: 'Writing research proposals and reports.',
    units: 2,
    yearLevel: '3rd',
    semester: '2nd',
    prerequisiteIds: ['ie-ipc-312'],
    syllabusUrl: 'https://example.com/syllabus/ie-ipc-323.pdf',
    icon: 'FileEdit'
  },
  {
    id: 'ie-ipc-324',
    code: 'IE - IPC 324/BA-M211',
    name: 'Marketing Management',
    description: 'Marketing strategies and consumer behavior.',
    units: 3,
    yearLevel: '3rd',
    semester: '2nd',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/ie-ipc-324.pdf',
    icon: 'Megaphone'
  },
  {
    id: 'ie-pe-322',
    code: 'IE - PE 322',
    name: 'Enterprise Resource Planning',
    description: 'Integrated business management systems.',
    units: 3,
    yearLevel: '3rd',
    semester: '2nd',
    prerequisiteIds: ['ie-pc-227'],
    syllabusUrl: 'https://example.com/syllabus/ie-pe-322.pdf',
    icon: 'Layers'
  },
  {
    id: 'gec-e',
    code: 'GEC - E',
    name: 'Ethics',
    description: 'Moral philosophy and ethical decision making.',
    units: 3,
    yearLevel: '3rd',
    semester: '2nd',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/gec-e.pdf',
    icon: 'BookText'
  },
  {
    id: 'gee-es',
    code: 'GEE-ES',
    name: 'Environmental Science',
    description: 'Environmental issues and sustainability.',
    units: 3,
    yearLevel: '3rd',
    semester: '2nd',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/gee-es.pdf',
    icon: 'Leaf'
  },

  // SUMMER
  {
    id: 'ie-pc-400',
    code: 'IE-PC 400',
    name: 'IE Industry Immersion',
    description: 'On-the-job training in an industrial setting.',
    units: 3,
    yearLevel: '4th',
    semester: 'Summer',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/ie-pc-400.pdf',
    icon: 'Building'
  },

  // FOURTH YEAR - 1st Semester
  {
    id: 'ie-pc-4116',
    code: 'IE - PC 4116',
    name: 'Project Feasibility',
    description: 'Preparation of project feasibility studies.',
    units: 3,
    yearLevel: '4th',
    semester: '1st',
    prerequisiteIds: ['ie-ac-314', 'ie-pc-3214'],
    syllabusUrl: 'https://example.com/syllabus/ie-pc-4116.pdf',
    icon: 'ClipboardCheck'
  },
  {
    id: 'ie-pc-4117',
    code: 'IE - PC 4117',
    name: 'Supply Chain Management',
    description: 'Logistics and supply chain optimization.',
    units: 3,
    yearLevel: '4th',
    semester: '1st',
    prerequisiteIds: ['ie-pc-3214'],
    syllabusUrl: 'https://example.com/syllabus/ie-pc-4117.pdf',
    icon: 'Truck'
  },
  {
    id: 'ie-pc-4118',
    code: 'IE - PC 4118',
    name: 'Systems Engineering',
    description: 'Design and management of complex systems.',
    units: 3,
    yearLevel: '4th',
    semester: '1st',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/ie-pc-4118.pdf',
    icon: 'Share2'
  },
  {
    id: 'ie-pe-413',
    code: 'IE-PE-413',
    name: 'Packaging Technology',
    description: 'Principles and materials of packaging.',
    units: 3,
    yearLevel: '4th',
    semester: '1st',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/ie-pe-413.pdf',
    icon: 'Box'
  },
  {
    id: 'ie-ac-415',
    code: 'IE - AC 415',
    name: 'Elementary Electrical Engineering',
    description: 'Basic electrical circuits and machines.',
    units: 3,
    yearLevel: '4th',
    semester: '1st',
    prerequisiteIds: ['ephys'],
    syllabusUrl: 'https://example.com/syllabus/ie-ac-415.pdf',
    icon: 'Zap'
  },
  {
    id: 'ie-ac-416',
    code: 'IE - AC 416',
    name: 'Environmental Engineering Sciences',
    description: 'Engineering solutions for environmental problems.',
    units: 3,
    yearLevel: '4th',
    semester: '1st',
    prerequisiteIds: ['gee-es'],
    syllabusUrl: 'https://example.com/syllabus/ie-ac-416.pdf',
    icon: 'Waves'
  },
  {
    id: 'gec-rph',
    code: 'GEC-RPH',
    name: 'Readings in Philippine History',
    description: 'Analysis of primary sources in Philippine history.',
    units: 3,
    yearLevel: '4th',
    semester: '1st',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/gec-rph.pdf',
    icon: 'Book'
  },

  // FOURTH YEAR - 2nd Semester
  {
    id: 'ie-pc-4219',
    code: 'IE - PC 4219',
    name: 'IE Capstone Project',
    description: 'Final design project for IE students.',
    units: 3,
    yearLevel: '4th',
    semester: '2nd',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/ie-pc-4219.pdf',
    icon: 'Flag'
  },
  {
    id: 'ie-pc-4220',
    code: 'IE - PC 4220',
    name: 'Engineering Values and Ethics',
    description: 'Professional ethics for engineers.',
    units: 3,
    yearLevel: '4th',
    semester: '2nd',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/ie-pc-4220.pdf',
    icon: 'ShieldAlert'
  },
  {
    id: 'ie-ipc-425',
    code: 'IE - IPC 425',
    name: 'Human Resource Planning',
    description: 'Management of human resources in industry.',
    units: 3,
    yearLevel: '4th',
    semester: '2nd',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/ie-ipc-425.pdf',
    icon: 'UserPlus'
  },
  {
    id: 'ie-pe-424',
    code: 'IE - PE 424',
    name: 'Lean Six Sigma',
    description: 'Methodologies for process improvement.',
    units: 3,
    yearLevel: '4th',
    semester: '2nd',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/ie-pe-424.pdf',
    icon: 'Compass'
  },
  {
    id: 'ie-pe-425',
    code: 'IE - PE 425',
    name: 'Intellectual Property Rights',
    description: 'Laws and principles of intellectual property.',
    units: 3,
    yearLevel: '4th',
    semester: '2nd',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/ie-pe-425.pdf',
    icon: 'Copyright'
  },
  {
    id: 'gec-aa',
    code: 'GEC - AA',
    name: 'Art Appreciation',
    description: 'Understanding and appreciating various art forms.',
    units: 3,
    yearLevel: '4th',
    semester: '2nd',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/gec-aa.pdf',
    icon: 'Palette'
  },
  {
    id: 'gec-sts',
    code: 'GEC - STS',
    name: 'Science, Technology and Society',
    description: 'Interaction between science, technology, and society.',
    units: 3,
    yearLevel: '4th',
    semester: '2nd',
    prerequisiteIds: [],
    syllabusUrl: 'https://example.com/syllabus/gec-sts.pdf',
    icon: 'Atom'
  },
];

export const ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-1',
    title: 'Final Examinations Schedule — May 11, 2026',
    content: 'The final examinations for the 2nd Semester AY 2025-2026 will be held from May 11 to May 16, 2026. Please check your department bulletin for the specific room assignments.',
    category: 'academic',
    isPinned: true,
    createdAt: '2026-04-10T08:00:00Z',
  },
  {
    id: 'ann-2',
    title: 'IE Department General Assembly — April 25, 2026',
    content: 'All IE students are required to attend the General Assembly at the CTU Main Gymnasium. Agenda includes curriculum updates and student organization elections.',
    category: 'event',
    isPinned: false,
    createdAt: '2026-04-12T10:00:00Z',
  },
  // More announcements...
];

export const CALENDAR_EVENTS: CalendarEvent[] = [
  {
    id: 'evt-1',
    title: 'Labor Day Holiday',
    date: '2026-05-01',
    category: 'holiday',
    description: 'No classes in observance of Labor Day.',
  },
  {
    id: 'evt-2',
    title: 'Final Exam Week',
    date: '2026-05-11',
    category: 'academic',
    description: 'Final examinations for all year levels.',
  },
];
